SHELL = /bin/bash

.PHONY: materials segments

materials:
	for module in materials/*/__illustrate__.py; do \
		python $$module; \
	done
segment_a:
	./segments/$@/__illustrate__.py
segment_b:
	./segments/$@/__illustrate__.py
segment_c:
	./segments/$@/__illustrate__.py
segment_d:
	./segments/$@/__illustrate__.py
segment_e:
	./segments/$@/__illustrate__.py
segment_f1:
	./segments/$@/__illustrate__.py
segment_f2:
	./segments/$@/__illustrate__.py
segment_g:
	./segments/$@/__illustrate__.py
segment_h:
	./segments/$@/__illustrate__.py
segment_i:
	./segments/$@/__illustrate__.py
segment_j:
	./segments/$@/__illustrate__.py
segment_k:
	./segments/$@/__illustrate__.py
segments: \
	segment_a \
	segment_b \
	segment_c \
	segment_d \
	segment_e \
	segment_f1 \
	segment_f2 \
	segment_g \
	segment_h \
	segment_i \
	segment_j \
	segment_k
