\include "../../../Abjad/consort/stylesheets/consort-header.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout.ily"
\include "../../../Abjad/consort/stylesheets/consort-paper.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout-electronics.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout-keyboards.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout-percussion.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout-strings.ily"
\include "../../../Abjad/consort/stylesheets/consort-layout-winds.ily"